# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 926485bdf986c83acdf59dd547f344e9802b4cafa6ae929d66de7b7b66a34992e568a1a074b4ed356462de2f96a018cb52475237fa51074a892fdb40b601548d

test:
  secret_key_base: 1ef35abd0fcece96b0abce7cf0ec879d6c25736e59a08effe7793e0af2fea843cd2c5e3130066cfe0996c558e7e4be3f3665a76693cbbb6e438b57da4c7bcbfb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
